### ISSUE TITLE
[FR] Sync TickTick tasks to corresponding folders in Obsidian

### ISSUE THREAD

**Issue by thesamim** [thesamim/TickTickSync#96]
### Discussed in https://github.com/thesamim/TickTickSync/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **radhakrisri** March 21, 2024</sup>
My TickTick is organized as lists under different folders for e.g..

- Household
- Career
  - Certifications (list)
  - Trainings (list)
- Projects
  - Project 1 (list)
  - Project 2 (list)

etc.

I have a similar folder structure in Obsidian too. When I setup tickticksync on obsidian, I had to setup a separate folder where all the tasks in ticktick are synced to.

Would be great, if the lists are synced to corresponding folders in Obsidian.</div>

**Comment by thesamim** [comment]
Fixed with release 2.0.1

**Comment by XCongoAlpha** [comment]
Checked this update if it works. Currently in TickTickSync 2.0.12
**Task Settings > Enable: Organize tasks by TickTick Folders**  -->  Yes Reorganize

After that obsidian **still does not** have the folder structure of TickTick
Inbox.md
Work.md
Completed.md

Instead of the intended folder structure
- Inbox
- Work
               [ ] Work 1.md
               [ ] Work 2.md
- Completed

**Comment by thesamim** [comment]
[....]
> Instead of the intended folder structure
[...]

Have you tried this:

<img width="577" height="137" alt="Image" src="https://github.com/user-attachments/assets/83620e0f-27f9-429e-825e-c240db5d8adc" />

**Comment by XCongoAlpha** [comment]
Yes, I have tried that too.

Even in these orders
Organize Tasks > Reset Tasks
Reset Tasks > Organize Tasks

**Comment by thesamim** [comment]
> Yes, I have tried that too.
> 
Under debug options: generate debug information and paste here.
Set Debug mode on and log level to Trace. Paste logs here.

**Comment by XCongoAlpha** [comment]
Here is the generated logs
````
{
  "general": {
    "version": "2.0.12",
    "baseURL": "ticktick.com",
    "enableFullVaultSync": false,
    "debugMode": true,
    "logLevel": "trace",
    "fileLinksInTickTick": "taskLink",
    "taskLinksInObsidian": "taskLink",
    "bkupFolder": "/",
    "skipBackup": false,
    "numProjects": 5,
    "fileTasks": [
      "Completed.md, 56",
      "Goals.md, 12",
      "IOS/IOS Sideloading.md, 0",
      "IOS/IOS Tips.md, 0",
      "Inbox.md, 0",
      "Obsidian/Obsidian Plugins.md, 0",
      "Personal.md, 24",
      "Work.md, 20"
    ]
  },
  "defaults": {
    "defaultProjectName": "Personal",
    "defaultProjectId": "5f3924b2e4f22102f0597793",
    "TickTickTasksFilePath": "/"
  },
  "syncControl": {
    "SyncProject": "",
    "tagAndOr": 1,
    "SyncTag": ""
  },
  "noteSetting": {
    "syncNotes": true,
    "noteDelimiter": "-------------------------------------------------------------"
  }
}
````

**Comment by thesamim** [comment]
The issue is that the flag is not set, we should see `keepProjectFolders": true,` in settings.

That flag is set when this checkbox is checked:

<img width="581" height="77" alt="Image" src="https://github.com/user-attachments/assets/d1d6458d-5cce-463d-bd2f-7efdb7381911" />

Can you confirm that it is checked? If it is, and it's still not working, can you tell me exactly what steps you took?

**Comment by XCongoAlpha** [comment]
New Vault with existing folder
Install TickTickSync > Login
Reorganize > Enable > Yes reorganize

**Result:**
Inbox.md
Work.md
Completed.md

**Instead of the intended ticktick folder structure**
    Inbox
    Work
      [ ] Work 1.md
      [ ] Work 2.md
    Completed

**Reset Tasks:**
OK
Same result
